# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/tarea2?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=fox17

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuracion del servidor
server.port=8080

# Configuracion de Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false

# Configuracion para archivos estaticos
spring.web.resources.static-locations=classpath:/static/
