# Configuracion temporal con H2 para pruebas
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuracion JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Configuracion del servidor
server.port=8080

# Configuracion H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false

# Configuracion para archivos estaticos
spring.web.resources.static-locations=classpath:/static/
